import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { stdout } from "node:process";

import { defaultConfigPath } from "../config.js";
import { listRegisteredProviders, getProvider } from "../providers/registry.js";
import type { Prompter } from "./prompts.js";
import { paint } from "./render.js";

export interface WizardResult {
  path: string;
  providerId: string;
  modelId: string;
}

interface ProviderChoice {
  id: string;
  label: string;
  hint?: string;
  signupUrl: string;
  keyPlaceholder: string;
}

const PROVIDER_BLURB: Record<string, Omit<ProviderChoice, "id" | "label">> = {
  cursor: {
    hint: "uses your Pro / Pro+ plan, no separate AI bill",
    signupUrl: "https://cursor.com/dashboard/integrations",
    keyPlaceholder: "Paste your Cursor API key (starts with `cursor_`)",
  },
  openai: {
    hint: "billing must be enabled on the OpenAI account",
    signupUrl: "https://platform.openai.com/api-keys",
    keyPlaceholder: "Paste your OpenAI API key (starts with `sk-`)",
  },
  anthropic: {
    hint: "anthropic.com console key",
    signupUrl: "https://console.anthropic.com/settings/keys",
    keyPlaceholder: "Paste your Anthropic API key (starts with `sk-ant-`)",
  },
};

/**
 * Walk the user through entering their GitHub PAT and one provider's API
 * key, then write a fresh config.toml. Always overwrites.
 */
export async function runInitWizard(
  prompter: Prompter,
  opts: { path?: string } = {},
): Promise<WizardResult> {
  const target = opts.path ?? defaultConfigPath();

  stdout.write(`${paint.bold("pr-review setup")}\n`);
  stdout.write(
    paint.dim(`We'll write your config to ${target}.\n`) +
      paint.dim("Keys are stored locally and never sent anywhere except the provider you pick.\n\n"),
  );

  stdout.write(`${paint.bold("1. GitHub")}\n`);
  stdout.write(
    paint.dim(
      "  Create a Personal Access Token (classic) with the `repo` scope at\n" +
        "  https://github.com/settings/tokens, then paste it below.\n",
    ),
  );
  const githubToken = await prompter.secret("  GitHub token");

  stdout.write(`\n${paint.bold("2. AI provider")}\n`);
  const providers = buildProviderChoices();
  const providerId = await prompter.choice(
    "  Which provider should review PRs?",
    providers.map((p) => ({ id: p.id, label: p.label, hint: p.hint })),
    { defaultId: providers[0]?.id ?? "cursor" },
  );

  const provider = providers.find((p) => p.id === providerId);
  if (!provider) {
    throw new Error(`Unknown provider: ${providerId}`);
  }

  stdout.write(`\n${paint.bold(`3. ${provider.label} API key`)}\n`);
  stdout.write(paint.dim(`  Get one at ${provider.signupUrl}\n`));
  const apiKey = await prompter.secret(`  ${provider.keyPlaceholder}`);

  const reg = getProvider(providerId);
  const modelChoices = reg.models.map((m) => ({ id: m.id, label: m.displayName }));
  const defaultModelId = modelChoices[0]?.id;
  let modelId = defaultModelId ?? "";
  if (modelChoices.length > 1) {
    stdout.write(`\n${paint.bold("4. Default model")}\n`);
    modelId = await prompter.choice(
      "  Pick a default model (you can override per-run with --model):",
      modelChoices,
      defaultModelId ? { defaultId: defaultModelId } : {},
    );
  }

  const toml = renderConfigToml({ githubToken, providerId, apiKey, modelId });
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, toml, { encoding: "utf8" });
  try {
    chmodSync(target, 0o600);
  } catch {
    // Best-effort on Windows where chmod is a no-op.
  }

  return { path: target, providerId, modelId };
}

function buildProviderChoices(): ProviderChoice[] {
  return listRegisteredProviders().map((p) => {
    const blurb = PROVIDER_BLURB[p.id];
    return {
      id: p.id,
      label: p.displayName,
      ...(blurb ?? {
        hint: undefined,
        signupUrl: "",
        keyPlaceholder: `Paste your ${p.displayName} API key`,
      }),
    } as ProviderChoice;
  });
}

function renderConfigToml(args: {
  githubToken: string;
  providerId: string;
  apiKey: string;
  modelId: string;
}): string {
  const { githubToken, providerId, apiKey, modelId } = args;

  const header = [
    "# pr-agent config",
    "# Generated by `pr-review init`. Rerun init to overwrite.",
  ];
  const github = ["[github]", `token = ${tomlString(githubToken)}`];
  const provider = [
    `[providers.${providerId}]`,
    `api_key = ${tomlString(apiKey)}`,
    ...(modelId ? [`default_model = ${tomlString(modelId)}`] : []),
  ];
  const defaults = [
    "[defaults]",
    `provider = ${tomlString(providerId)}`,
    ...(modelId ? [`model = ${tomlString(modelId)}`] : []),
    "post_review = true",
  ];

  return [header, github, provider, defaults]
    .map((section) => section.join("\n"))
    .join("\n\n") + "\n";
}

function tomlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
